import numpy as np
from pathlib import Path

NUM_SLICES: int = 6
BITS_PER_SLICE: int = 2
SLICE_MASK: int = (1 << BITS_PER_SLICE) - 1

EMPTY: int = 0
BLUE: int = 1
RED: int = 2
BOTH: int = 3

COLOR_SET: list[int] = [EMPTY, BLUE, RED]

def generate_constants() -> None:
    num_possible: int = 1 << (BITS_PER_SLICE * NUM_SLICES)
    
    color_slice_score: np.ndarray = np.zeros(
        (len(COLOR_SET), NUM_SLICES), dtype=np.uint64
    )
    for color in COLOR_SET:
        for slice_idx in range(NUM_SLICES):
            shift: int = slice_idx * BITS_PER_SLICE
            color_slice_score[color, slice_idx] = color << shift
    
    mask_slice_score: np.ndarray = np.zeros(NUM_SLICES, dtype=np.uint64)
    for slice_idx in range(NUM_SLICES):
        shift: int = slice_idx * BITS_PER_SLICE
        mask_slice_score[slice_idx] = SLICE_MASK << shift
    
    shift_values: np.ndarray = np.arange(NUM_SLICES, dtype=np.int32) * BITS_PER_SLICE
    
    values: np.ndarray = np.arange(num_possible, dtype=np.uint64)
    valid_mask: np.ndarray = np.ones(num_possible, dtype=bool)
    
    for slice_idx in range(NUM_SLICES):
        shift: int = slice_idx * BITS_PER_SLICE
        slice_values: np.ndarray = (values >> shift) & SLICE_MASK
        slice_valid: np.ndarray = slice_values <= 3
        valid_mask &= slice_valid
    
    valid_godels: np.ndarray = values[valid_mask].astype(np.uint64)
    
    godel_to_index: np.ndarray = np.full(num_possible, -1, dtype=np.int64)
    for idx, godel in enumerate(valid_godels):
        godel_to_index[int(godel)] = idx
    
    output_code: str = '''# AUTOGENERATED — do not edit
import numpy as np

NUM_SLICES: int = 6
BITS_PER_SLICE: int = 2
SLICE_MASK: int = 3

EMPTY: int = 0
BLUE: int = 1
RED: int = 2
BOTH: int = 3

EMPTY_RING_VALUE: int = 0

'''
    
    output_code += _format_array(
        "COLOR_SLICE_SCORE", color_slice_score, "uint64"
    )
    output_code += "\n"
    output_code += _format_array(
        "MASK_SLICE_SCORE", mask_slice_score, "uint64"
    )
    output_code += "\n"
    output_code += _format_array(
        "VALID_GODELS", valid_godels, "uint64"
    )
    output_code += "\n"
    output_code += _format_array(
        "GODEL_TO_INDEX", godel_to_index, "int64"
    )
    output_code += "\n"
    output_code += _format_array(
        "SHIFT_VALUES", shift_values, "int32"
    )
    
    output_path: Path = Path(__file__).parent / "ring_constants.py"
    output_path.write_text(output_code)
    print(f"Generated {output_path}")

def _format_array(name: str, arr: np.ndarray, dtype_str: str) -> str:
    if arr.ndim == 1:
        values_str: str = ", ".join(str(int(v)) for v in arr)
        return f"{name}: np.ndarray = np.array([{values_str}], dtype=np.{dtype_str})\n"
    elif arr.ndim == 2:
        rows: list[str] = []
        for row in arr:
            row_str: str = ", ".join(str(int(v)) for v in row)
            rows.append(f"    [{row_str}]")
        rows_joined: str = ",\n".join(rows)
        return f"{name}: np.ndarray = np.array([\n{rows_joined}\n], dtype=np.{dtype_str})\n"
    else:
        raise ValueError(f"Unsupported array dimension: {arr.ndim}")

if __name__ == "__main__":
    generate_constants()