#!/usr/bin/env python3
# pipeline/scripts/precompute_neighbors_lookup.py

"""
Precompute Neighbors Lookup
----------------------------
Generates a 2D NumPy array for O(1) neighbor lookups on hex boards.

Outputs:
    pipeline/out/neighbors_lookup.py
"""

import os
import sys
import numpy as np
from typing import List, Tuple

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from pipeline.out.local_pattern_table import INDEX_TO_CELL, OFFSET_LIST

from pipeline.out.cell_to_index_lookup import CELL_TO_INDEX_LOOKUP

BOARD_SIZE = 14
OUTPUT_DIR = "pipeline/out"
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "neighbors_lookup.py")


def get_hex_neighbors(q: int, r: int, board_size: int) -> List[Tuple[int, int]]:
    directions: List[Tuple[int, int]] = [
        (0, -1), (1, -1), (-1, 0),
        (1, 0), (-1, 1), (0, 1)
    ]
    neighbors: List[Tuple[int, int]] = []
    for dq, dr in directions:
        nq, nr = q + dq, r + dr
        if 0 <= nq < board_size and 0 <= nr < board_size:
            neighbors.append((nq, nr))
    return neighbors


def compute_neighbors_lookup(board_size: int) -> Tuple[np.ndarray, int]:
    """Precompute 2D neighbors lookup array.
    
    Returns:
        lookup: shape (total_cells, max_neighbors) with -1 padding
        max_neighbors: maximum neighbors any cell has
    """
    total_cells = board_size * board_size
    neighbors_list: List[List[int]] = []
    
    for cell_idx in range(total_cells):
        q = cell_idx // board_size
        r = cell_idx % board_size
        
        neighbor_coords = get_hex_neighbors(q, r, board_size)
        neighbor_indices: List[int] = [nq * board_size + nr for nq, nr in neighbor_coords]
        neighbors_list.append(neighbor_indices)
    
    max_neighbors = max(len(n) for n in neighbors_list)
    lookup = np.full((total_cells, max_neighbors), -1, dtype=np.int32)
    
    for cell_idx, neighbors in enumerate(neighbors_list):
        lookup[cell_idx, :len(neighbors)] = neighbors
    
    return lookup, max_neighbors


def write_neighbors_lookup(lookup: np.ndarray, max_neighbors: int, output_file: str) -> None:
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    with open(output_file, "w") as f:
        f.write("# ======================================================\n")
        f.write("# Auto-generated Neighbors Lookup - DO NOT EDIT\n")
        f.write("# ======================================================\n")
        f.write("# 2D NumPy array for O(1) neighbor lookups\n")
        f.write("# Shape: (total_cells, max_neighbors)\n")
        f.write("# Padding value: -1 (indicates no neighbor)\n")
        f.write("# ======================================================\n\n")
        
        f.write("import numpy as np\n\n")
        
        f.write(f"MAX_NEIGHBORS = {max_neighbors}\n")
        f.write(f"TOTAL_CELLS = {lookup.shape[0]}\n\n")
        
        f.write("NEIGHBORS_LOOKUP = np.array(\n")
        f.write(repr(lookup.tolist()))
        f.write(", dtype=np.int32)\n")
    
    print(f"✅ Neighbors lookup written to {output_file}")
    print(f"   - Shape: {lookup.shape}")
    print(f"   - Max neighbors per cell: {max_neighbors}")
    print(f"   - Total cells: {lookup.shape[0]}")


# --- NEW: Precompute (center_idx, offset_idx) → neighbor_idx and reverse mapping ---
def precompute_neighbor_offset_tables(
    board_size: int,
    offset_list: List[Tuple[int, int]],
    cell_to_index_lookup: np.ndarray
) -> Tuple[np.ndarray, List[List[Tuple[int, int]]]]:
    """Build NEIGHBOR_TABLE using true axial coordinates and skip center (0,0)."""
    filtered_offsets = [offset for offset in offset_list if offset != (0, 0)]
    total_cells = board_size * board_size
    num_offsets = len(filtered_offsets)
    neighbor_table = np.full((total_cells, num_offsets), -1, dtype=np.int32)
    affected_table: List[List[Tuple[int, int]]] = [[] for _ in range(total_cells)]

    for center_idx in range(total_cells):
        center_q, center_r = INDEX_TO_CELL[center_idx]
        for offset_idx, (dq, dr) in enumerate(filtered_offsets):
            nq = int(center_q) + dq
            nr = int(center_r) + dr
            if 0 <= nq < board_size and 0 <= nr < board_size:
                neighbor_idx = int(cell_to_index_lookup[nq, nr])
                neighbor_table[center_idx, offset_idx] = neighbor_idx
                affected_table[neighbor_idx].append((center_idx, offset_idx))
    return neighbor_table, affected_table


def python_literal_neighbor_tables(
    neighbor_table: np.ndarray,
    affected_table: List[List[Tuple[int, int]]],
) -> str:
    lines: List[str] = []
    lines.append("# Auto-generated by pipeline/scripts/precompute_neighbors_lookup.py")
    lines.append("")
    nb_table: List[List[int]] = neighbor_table.tolist()
    lines.append(f"NEIGHBOR_TABLE = {nb_table}")
    lines.append("")
    # Inline list literal for affected_reverse_table
    affected_literal = [[(int(pair[0]), int(pair[1])) for pair in entry] for entry in affected_table]
    lines.append(f"AFFECTED_REVERSE_TABLE = {affected_literal}")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    print(f"🔧 Precomputing neighbors lookup for {BOARD_SIZE}x{BOARD_SIZE} board...")
    
    lookup, max_neighbors = compute_neighbors_lookup(BOARD_SIZE)
    write_neighbors_lookup(lookup, max_neighbors, OUTPUT_FILE)
    
    # --- NEW neighbor-offset flat tables ---
    # Derive offsets from the builder's OFFSET_LIST to guarantee identical ordering.
    # OFFSET_LIST must be center-inclusive at index 0.
    assert len(OFFSET_LIST) >= 13 and tuple(OFFSET_LIST[0]) == (0, 0), "OFFSET_LIST must start with center (0,0)"
    neighbor_table, affected_table = precompute_neighbor_offset_tables(
        BOARD_SIZE, [(int(x[0]), int(x[1])) for x in OFFSET_LIST], CELL_TO_INDEX_LOOKUP
    )
    # neighbor_table now shape (total_cells, len(OFFSET_LIST))
    
    out_py = "pipeline/out/neighbor_offset_tables.py"
    py_str = python_literal_neighbor_tables(neighbor_table, affected_table)
    with open(out_py, "w", encoding="utf-8") as f:
        f.write(py_str)
    print(f"✅ neighbor_offset_tables.py written to {out_py}")
    print("➡️  Copy this file to src/precomputed/ for engine import.")
    
    print("✨ Done!")