import numpy as np

MATCH_MODE_FIRST = 0
MATCH_MODE_ALL = 1

PATTERN_MAX_RADIUS = 3
PATTERN_PRIMARY_MOVE_RADIUS = 2
PATTERN_NUM_SLICES = 6
SLICE_NUM_FEATURE_TYPES = 5

SLICE_FEATURE_CELLS = 0
SLICE_FEATURE_RED_STONES = 1
SLICE_FEATURE_BLUE_STONES = 2
SLICE_FEATURE_PRIMARY_MARKED = 3
SLICE_FEATURE_SECONDARY_MARKED = 4

FLAG_HAS_EMPTY_CELLS = 1 << 0
FLAG_HAS_PRIMARY_MOVES = 1 << 1
FLAG_HAS_SECONDARY_MOVES = 1 << 2
FLAG_HAS_WEIGHT_VALUE = 1 << 3

TYPE_UNSPECIFIED = ' '
TYPE_NEUTRAL_FILL = 'e'
TYPE_BLUE_CAPTURE_FILL = 'f'
TYPE_BLUE_STRONG_REVERSAL = 's'
TYPE_BLUE_THREAT_REVERSAL = 't'
TYPE_BLUE_INFERIOR_MOVE = 'i'
TYPE_BLUE_REVERSIBLE = 'r'
TYPE_VC_CAPTURE = 'c'

CELL_EMPTY = 0
CELL_BLUE = 1
CELL_RED = 2

MAX_SLICE_BITS = PATTERN_MAX_RADIUS * (PATTERN_MAX_RADIUS + 1) // 2
BIT_MASKS = np.array([1 << i for i in range(MAX_SLICE_BITS)], dtype=np.uint32)